"""add_idempotency_and_callback_to_execution

Revision ID: be0dbc8b4bc3
Revises: 4d08065d1da8
Create Date: 2026-06-29 10:19:37.862825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0dbc8b4bc3'
down_revision: Union[str, Sequence[str], None] = '4d08065d1da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_executions', sa.Column('client_request_id', sa.String(), nullable=True))
    op.add_column('agent_executions', sa.Column('callback_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_agent_executions_client_request_id'), 'agent_executions', ['client_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_executions_client_request_id'), table_name='agent_executions')
    op.drop_column('agent_executions', 'callback_url')
    op.drop_column('agent_executions', 'client_request_id')
    # ### end Alembic commands ###
